### PR TITLE
Update for Multi Fix Format

### PR DESCRIPTION
**Pull request by kmalyar-tic**
Hi,

As mentioned, I am really new to Logstash and FIX.  This is what seems to have worked for us.  I hope this is helpful.  Obviously feel free to tweak or tell me what to tweak.

Regards,
Kelvin

### CODE REVIEW

**Comment by daino3** [comment]
This looks good to me. I'll let others complain if this configuration doesn't work for them.

**Comment by daino3** [comment]
@cbusbey - can you merge?

**Comment by cbusbey** [comment]
Thanks for the contribution! 🍻

**Comment by GJB-ICM** [comment]
Like kmalyar-tic I'm new to Logstash.
I have a FIX server which takes in many connections of various FIX versions. I have been attempting to get the multi fix protocol input filter to work.

However when loading any quickfix data dictionaries other than 4.2 I get an error ... The conf is a copy of the multi protocol portion in the readme with paths updated. The issue seems to occur with message-types beyond that in v4.2 ... Below is the log showing v4.2 loading fine followed by 4.4 failing:

[2017-07-10T11:46:30,104][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"fix_protocol", :type=>"filter", :class=>LogStash::Filters::FixProtocol}
[2017-07-10T11:46:30,111][INFO ][logstash.filters.fixprotocol] Using version 0.1.x filter plugin 'fix_protocol'. This plugin isn't well supported by the community and likely has no maintainer.
[2017-07-10T11:46:30,112][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@fix_message = "fix_string"
[2017-07-10T11:46:30,113][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@data_dictionary_path = "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/spec/fixtures/FIX42.xml"
[2017-07-10T11:46:30,114][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@id = "9ab8985be48cdde0a04190148e9b0fe0d9a95aef-3"
[2017-07-10T11:46:30,114][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@enable_metric = true
[2017-07-10T11:46:30,116][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@add_tag = []
[2017-07-10T11:46:30,116][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@remove_tag = []
[2017-07-10T11:46:30,116][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@add_field = {}
[2017-07-10T11:46:30,117][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@remove_field = []
[2017-07-10T11:46:30,117][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@periodic_flush = false
[2017-07-10T11:46:30,117][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@session_dictionary_path = nil
[2017-07-10T11:46:30,305][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@fix_message = "fix_string"
[2017-07-10T11:46:30,310][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@data_dictionary_path = "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/spec/fixtures/FIX44.xml"
[2017-07-10T11:46:30,311][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@id = "9ab8985be48cdde0a04190148e9b0fe0d9a95aef-4"
[2017-07-10T11:46:30,311][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@enable_metric = true
[2017-07-10T11:46:30,311][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@add_tag = []
[2017-07-10T11:46:30,311][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@remove_tag = []
[2017-07-10T11:46:30,311][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@add_field = {}
[2017-07-10T11:46:30,311][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@remove_field = []
[2017-07-10T11:46:30,312][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@periodic_flush = false
[2017-07-10T11:46:30,312][DEBUG][logstash.filters.fixprotocol] config LogStash::Filters::FixProtocol/@session_dictionary_path = nil
[2017-07-10T11:46:30,390][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Constructor invocation failed: No fields found: msgType=n", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/data_dictionary.rb:11:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/fix_protocol.rb:28:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:21:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:96:in `plugin'", "(eval):68:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:63:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:145:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:286:in `create_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:274:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:185:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}

ELK Stack as well as your plugin are all the latest versions running on Ubuntu 14.04.
Any advice would be greatly appreciated.

**Comment by kmalyar-tic** [comment]
@GJB-ICM 

Could you share your conf file?  I ran across something very similar to this.

This stackoverflow thread ended up helping a lot:
https://stackoverflow.com/questions/22941666/quickfix-configuration-failed-message-contains-no-fields

**Comment by GJB-ICM** [comment]
Sure no problem. Attached



________________________________
Gary Brown
Infinity Capital Markets Ltd
80 Coleman Street, 1st Floor,
London EC2R 5BJ, United Kingdom
Office: +44 (0)20 7653 8874
Mobile: +44 (0)7980 288 275
IT Support: +44 (0)20 7653 8867
Internet: G.Brown@infinitycm.co.uk<mailto:G.Brown@infinitycm.co.uk>

**Comment by kmalyar-tic** [comment]
@GJB-ICM 

The attachment didn't come through.  I think you can just paste the config file into the comment itself.

**Comment by GJB-ICM** [comment]
As per your link stripping out this line solved the problem for v4.4:

  <message name='XMLnonFIX' msgtype='n' msgcat='admin' />

Thank you very much for that … FYI the conf file contents are below:


input {
  file {
    path => "/usr/share/logstash/spiderlogs/spider.*"
    start_position => "beginning"
  }
}
filter {
  grok {
    match => ["message","%{GREEDYDATA:fix_string}"]
  }
  if [fix_string] =~ "=FIX.4.2" {
    fix_protocol {
      fix_message => fix_string
      data_dictionary_path => "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/spec/fixtures/FIX42.xml"
    }
  }
  if [fix_string] =~ "=FIX.4.4" {
    fix_protocol {
      fix_message => fix_string
      data_dictionary_path => "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/spec/fixtures/FIX44.xml"
    }
  }
  if [fix_string] =~ "=FIX.5.0" {
    fix_protocol {
      fix_message => fix_string
      session_dictionary_path => "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/spec/fixtures/FIXT11.xml"
      data_dictionary_path => "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/spec/fixtures/FIX50.xml"
    }
  }
  else {
    drop {}
  }
}

________________________________
Gary Brown
Infinity Capital Markets Ltd
80 Coleman Street, 1st Floor,
London EC2R 5BJ, United Kingdom
Office: +44 (0)20 7653 8874
Mobile: +44 (0)7980 288 275
IT Support: +44 (0)20 7653 8867
Internet: G.Brown@infinitycm.co.uk<mailto:G.Brown@infinitycm.co.uk>

**Pull request merged**
