### PR TITLE
Issue 77 nested sub groups

### LINKED ISSUE #77: Fatal Exception on Nested Groups/SubGroups
Hi @daino3 ,

We have a message with (FIXv4.4) and it uses the group and then subgroup tags.

eg:
field number='453' name='NoPartyIDs' type='NUMINGROUP' 
and
field number='802' name='NoPartySubIDs' type='NUMINGROUP' 

It crashes when it finds another group (beyond the first level it seems like)

`[2017-06-21T11:06:35,571][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' for #<Java::Quickfix::Group:0x3478b854>", "backtrace"=>["/home/kmalyar/tmp/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/fix_message.rb:87:in `field_map_to_hash'", "/home/kmalyar/tmp/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/fix_message.rb:72:in `field_map_to_hash'", "org/jruby/RubyRange.java:479:in `each'", "/home/kmalyar/tmp/logstash/vendor/bundle/jruby/1.9/gems/activesupport-4.1.16/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'", "/home/kmalyar/tmp/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/fix_message.rb:69:in `field_map_to_hash'", "/home/kmalyar/tmp/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/fix_message.rb:25:in `to_hash'", "/home/kmalyar/tmp/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fix_protocol-0.3.1/lib/logstash/filters/fix_protocol.rb:52:in `filter'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'", "(eval):211:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):203:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):142:in `filter_func'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:370:in `filter_batch'", "org/jruby/RubyProc.java:281:in `call'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `each'", "org/jruby/RubyHash.java:1342:in `each'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:369:in `filter_batch'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:350:in `worker_loop'", "/home/kmalyar/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"]}
`

Have you run into this before?

Thanks!
Kelvin

### PR DESCRIPTION
**Pull request by daino3**
+ should close #77 

ping: @kmalyar-tic - take a look at the [test](https://github.com/connamara/logstash-filter-fix_protocol/pull/78/files#diff-787b62582c03a5736b773d6742f2960aR271). I believe this fixes the issue you're seeing. 

ping: @cbusbey - please review & merge when you get a chance.

### CODE REVIEW

**Comment by cbusbey** [comment]
Thanks @daino3 🐐 🍰

**Comment by kmalyar-tic** [comment]
Hey Guys,

This is awesome.  Thanks so much for the turnaround.  From my side I have a dumb question.  Not being familiar with Ruby, how do I update my logstash install with this?  Is it publisehd to their repo or is there a quick way for me to load from the git repo/fork (build the project locally)?

**Comment by cbusbey** [comment]
@kmalyar-tic take a look at the readme section on development.

https://github.com/connamara/logstash-filter-fix_protocol#development-logstash-installation

Alternatively, you can build the gem locally and deploy to your environment (run `rake -T` to get the appropriate build gem task name).  This change will eventually make it into the official release that makes its way to rubygems.

**Comment by kmalyar-tic** [comment]
@cbusbey,

I've found something disconcerting.  I don't have the ability to install any packages as I'm using /usr/bin/ruby.

I tried the following:

 $ gem build logstash-filter-fix_protocol.gemspec
ERROR:  While executing gem ... (NoMethodError)


Installing bundler and other tools didn't work as I don't have permission to the relevant directory:
```

 ~/git/3rd_party/logstash-filter-fix_protocol [master] $ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /usr/lib/ruby/gems/1.8 directory.

```

Any chance you can help get a hold of the gem, or let me know when you guys will be able to push the gem out for updating?

(I know this is a bit annoying for you, I'd be happy to do it, but I seem to be handicapped in this)

**Comment by daino3** [comment]
gents - I'll release once the [version bump is merged](https://github.com/connamara/logstash-filter-fix_protocol/pull/79)

@kmalyar-tic - to update to the latest release see [this guy](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#updating-plugins):

**Comment by kmalyar-tic** [comment]
You are both, scholars and gentlemen.  Thanks again!


Regards,
Kelvin

p.s I've been modifing my working environment with new gems folders and path hacking.  I think I was almost there, but your approach is ideal!

**Comment by daino3** [comment]
@kmalyar-tic - the latest gem is published as v `0.3.2` - go ahead and update and let me know if everything is A-OK.

**Pull request merged**
